# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr_FR

services:
    # Default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services
        autowire: true

        # Automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

        # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work
        public: false

    #app.form.extension.type.order_item:
        #class: App\Form\Extension\CartItemTypeExtension
        #tags:
            #- { name: form.type_extension, extended_type: Sylius\Bundle\OrderBundle\Form\Type\CartItemType }

    app.provider.order:
        class: App\Provider\Order
        arguments: ['@sylius.repository.order_item']
        public: false
           
    


    #app.form.extension.type.cart_item:
        #class: App\Form\Extension\CartItemTypeExtension
        #tags:
           # - { name: form.type_extension, extended_type: Sylius\Bundle\OrderBundle\Form\Type\CartItemType }

    app.order_resource_controller:
        class: App\Controller\Order\OrderResourceController
        public: true

    app..infos_controller:
        class: App\Controller\Infos\InfosController
        public: true

    App\Controller\Order\OrderItemController:
        autowire: true

    App\Controller\OrderResourceController:
        autowire: true

    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false
        Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
            autowire: false

    # Makes classes in src/ available to be used as services;
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # Controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
